// <auto-generated />
using System;
using KonferansPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KonferansPortal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241120140517_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgitmenKonferans", b =>
                {
                    b.Property<int>("EgitilenKonferansId")
                        .HasColumnType("int");

                    b.Property<int>("EgitmenlerId")
                        .HasColumnType("int");

                    b.HasKey("EgitilenKonferansId", "EgitmenlerId");

                    b.HasIndex("EgitmenlerId");

                    b.ToTable("EgitmenKonferans");
                });

            modelBuilder.Entity("KatilimciKonferans", b =>
                {
                    b.Property<int>("KatilimcilarId")
                        .HasColumnType("int");

                    b.Property<int>("KatilinanKonferansId")
                        .HasColumnType("int");

                    b.HasKey("KatilimcilarId", "KatilinanKonferansId");

                    b.HasIndex("KatilinanKonferansId");

                    b.ToTable("KatilimciKonferans");
                });

            modelBuilder.Entity("KonferansPortal.Models.Konferans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Konferanslar");
                });

            modelBuilder.Entity("KonferansPortal.Models.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uyeler");

                    b.HasDiscriminator().HasValue("Uye");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("KonferansPortal.Models.Egitmen", b =>
                {
                    b.HasBaseType("KonferansPortal.Models.Uye");

                    b.HasDiscriminator().HasValue("Egitmen");
                });

            modelBuilder.Entity("KonferansPortal.Models.Katilimci", b =>
                {
                    b.HasBaseType("KonferansPortal.Models.Uye");

                    b.HasDiscriminator().HasValue("Katilimci");
                });

            modelBuilder.Entity("EgitmenKonferans", b =>
                {
                    b.HasOne("KonferansPortal.Models.Konferans", null)
                        .WithMany()
                        .HasForeignKey("EgitilenKonferansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KonferansPortal.Models.Egitmen", null)
                        .WithMany()
                        .HasForeignKey("EgitmenlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KatilimciKonferans", b =>
                {
                    b.HasOne("KonferansPortal.Models.Katilimci", null)
                        .WithMany()
                        .HasForeignKey("KatilimcilarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KonferansPortal.Models.Konferans", null)
                        .WithMany()
                        .HasForeignKey("KatilinanKonferansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
